# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd46aa903228c1d4b59b5dc5db24590875c581e920910c28e922c8a74386a220c749ab44ac0e63e48241e09b9d60674efce238cfc7212ce4617d4d3c43f295f1

test:
  secret_key_base: 4cc9fa60b23ee0db42155a59cb8ed8301cbf39d884afd169a677f649eba06745b62f562a4333bd8cf1187ce24c87f7cbc8e8901091e4d25106f0735dd67ca29a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
